services:
  db:
   image: postgres:17
   ports:
     - "5432:5432"
   volumes:
     - ./.docker/postgres:/app/db
   env_file:
     - ./src/.env
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8000:8000"
    env_file:
     - ./src/.env
    depends_on:
      - db
    volumes:
      - ./src:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/app/db

  djangoq:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py qcluster
    env_file:
     - ./src/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    volumes:
      - ./.docker/mailhog:/app/db