services:
  db:
   image: postgres:17
   ports:
     - "5432:5432"
   volumes:
     - ./.docker/postgres:/app/db
   env_file:
     - ./src/.env
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8000:8000"
    env_file:
     - ./src/.env
    depends_on:
      - db
    volumes:
      - ./src:/app