# Generated by Django 5.2.1 on 2025-05-25 18:24

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_plans_info_pro(apps, schema_editor):
    """
    Create SubscriptionPlan objects for the 'info_pro' plan.
    """
    POWER = "power"
    TAX = "tax"
    HEALTH = "health"
    ENERGY = "energy"
    LABOR = "labor"
    SubscriptionPlan = apps.get_model("account", "SubscriptionPlan")
    SubscriptionPlan.objects.create(
        name="Info",
        price=0,
        verticals=[],
    )
    SubscriptionPlan.objects.create(
        name="Pro",
        price=29.99,
        verticals=[
            POWER,
            TAX,
            HEALTH,
            ENERGY,
            LABOR,
        ],
        is_exclusive=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_plans_info_pro, reverse_code=migrations.RunPython.noop
        ),
    ]
